services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=test_database'
      - 'POSTGRES_PASSWORD=Y8qE5UmB'
      - 'POSTGRES_USER=api_user'
    ports:
      - "5432:5432"
